name: manually-running-a-workflow
on:
  workflow_dispatch:
    inputs:
      git_sha:
        description: "Please provide the version you would like to build (SHA-1)."
        required: true
        type: string
      doubleCheck:
        description: "If you're aware that submitting will trigger SHA-1 and replace the build, please check the box."
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          ENV: staging-test-ENV
          NODE_ENV: staging-NODE_ENV
          GIT_SHA: ${{inputs.git_sha}}
        run: |
          echo "seems this is ok git_sha: ${{inputs.git_sha}} " 
          echo "time to log env var: $SHA " 
          echo "Add other actions to build,"
          echo test, and deploy your project.
          echo "name=image::$ENV/$NODE_ENV test for string concat" >> $GITHUB_OUTPUT


      - name: test condition true
        if: inputs.doubleCheck == true
        run: |
          echo "if: github.event.inputs.doubleCheck == true" 
          echo test condition true


      - name: test condition false
        if: inputs.doubleCheck == false
        run: |
          echo "if: github.event.inputs.doubleCheck == false" 
          echo test condition false


